/* tslint:disable */
/* eslint-disable */
/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * The version of the OpenAPI document: v0.11.1
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GenericError } from './GenericError';
import {
    GenericErrorFromJSON,
    GenericErrorFromJSONTyped,
    GenericErrorToJSON,
} from './GenericError';

/**
 * The standard Ory JSON API error format.
 * @export
 * @interface ErrorGeneric
 */
export interface ErrorGeneric {
    /**
     * 
     * @type {GenericError}
     * @memberof ErrorGeneric
     */
    error: GenericError;
}

/**
 * Check if a given object implements the ErrorGeneric interface.
 */
export function instanceOfErrorGeneric(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "error" in value;

    return isInstance;
}

export function ErrorGenericFromJSON(json: any): ErrorGeneric {
    return ErrorGenericFromJSONTyped(json, false);
}

export function ErrorGenericFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorGeneric {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'error': GenericErrorFromJSON(json['error']),
    };
}

export function ErrorGenericToJSON(value?: ErrorGeneric | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'error': GenericErrorToJSON(value.error),
    };
}

