/* tslint:disable */
/* eslint-disable */
/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * The version of the OpenAPI document: v0.11.1
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthNotReadyStatus
 */
export interface HealthNotReadyStatus {
    /**
     * Errors contains a list of errors that caused the not ready status.
     * @type {{ [key: string]: string; }}
     * @memberof HealthNotReadyStatus
     */
    errors?: { [key: string]: string; };
}

/**
 * Check if a given object implements the HealthNotReadyStatus interface.
 */
export function instanceOfHealthNotReadyStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HealthNotReadyStatusFromJSON(json: any): HealthNotReadyStatus {
    return HealthNotReadyStatusFromJSONTyped(json, false);
}

export function HealthNotReadyStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthNotReadyStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errors': !exists(json, 'errors') ? undefined : json['errors'],
    };
}

export function HealthNotReadyStatusToJSON(value?: HealthNotReadyStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errors': value.errors,
    };
}

