/* tslint:disable */
/* eslint-disable */
/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * The version of the OpenAPI document: v0.11.1
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The state can either be `active` or `inactive`.
 * @export
 */
export const IdentityState = {
    Active: 'active',
    Inactive: 'inactive'
} as const;
export type IdentityState = typeof IdentityState[keyof typeof IdentityState];


export function IdentityStateFromJSON(json: any): IdentityState {
    return IdentityStateFromJSONTyped(json, false);
}

export function IdentityStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityState {
    return json as IdentityState;
}

export function IdentityStateToJSON(value?: IdentityState | null): any {
    return value as any;
}

