/* tslint:disable */
/* eslint-disable */
/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * The version of the OpenAPI document: v0.11.1
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An Identity JSON Schema Container
 * @export
 * @interface IdentitySchemaContainer
 */
export interface IdentitySchemaContainer {
    /**
     * The ID of the Identity JSON Schema
     * @type {string}
     * @memberof IdentitySchemaContainer
     */
    id?: string;
    /**
     * Raw JSON Schema
     * @type {object}
     * @memberof IdentitySchemaContainer
     */
    schema?: object;
}

/**
 * Check if a given object implements the IdentitySchemaContainer interface.
 */
export function instanceOfIdentitySchemaContainer(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function IdentitySchemaContainerFromJSON(json: any): IdentitySchemaContainer {
    return IdentitySchemaContainerFromJSONTyped(json, false);
}

export function IdentitySchemaContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentitySchemaContainer {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'schema': !exists(json, 'schema') ? undefined : json['schema'],
    };
}

export function IdentitySchemaContainerToJSON(value?: IdentitySchemaContainer | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'schema': value.schema,
    };
}

