/* tslint:disable */
/* eslint-disable */
/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * The version of the OpenAPI document: v0.11.1
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * and so on.
 * @export
 */
export const IdentityCredentialsType = {
    Password: 'password',
    Totp: 'totp',
    Oidc: 'oidc',
    Webauthn: 'webauthn',
    LookupSecret: 'lookup_secret'
} as const;
export type IdentityCredentialsType = typeof IdentityCredentialsType[keyof typeof IdentityCredentialsType];


export function IdentityCredentialsTypeFromJSON(json: any): IdentityCredentialsType {
    return IdentityCredentialsTypeFromJSONTyped(json, false);
}

export function IdentityCredentialsTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IdentityCredentialsType {
    return json as IdentityCredentialsType;
}

export function IdentityCredentialsTypeToJSON(value?: IdentityCredentialsType | null): any {
    return value as any;
}

