/* tslint:disable */
/* eslint-disable */
/**
 * Ory Identities API
 * This is the API specification for Ory Identities with features such as registration, login, recovery, account verification, profile settings, password reset, identity management, session management, email and sms delivery, and more. 
 *
 * The version of the OpenAPI document: v0.11.1
 * Contact: office@ory.sh
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * nolint:deadcode,unused
 * @export
 * @interface UpdateSettingsFlowWithOidcMethod
 */
export interface UpdateSettingsFlowWithOidcMethod {
    /**
     * Flow ID is the flow's ID.
     * 
     * in: query
     * @type {string}
     * @memberof UpdateSettingsFlowWithOidcMethod
     */
    flow?: string;
    /**
     * Link this provider
     * 
     * Either this or `unlink` must be set.
     * 
     * type: string
     * in: body
     * @type {string}
     * @memberof UpdateSettingsFlowWithOidcMethod
     */
    link?: string;
    /**
     * Method
     * 
     * Should be set to profile when trying to update a profile.
     * @type {string}
     * @memberof UpdateSettingsFlowWithOidcMethod
     */
    method: string;
    /**
     * The identity's traits
     * 
     * in: body
     * @type {object}
     * @memberof UpdateSettingsFlowWithOidcMethod
     */
    traits?: object;
    /**
     * Unlink this provider
     * 
     * Either this or `link` must be set.
     * 
     * type: string
     * in: body
     * @type {string}
     * @memberof UpdateSettingsFlowWithOidcMethod
     */
    unlink?: string;
}

/**
 * Check if a given object implements the UpdateSettingsFlowWithOidcMethod interface.
 */
export function instanceOfUpdateSettingsFlowWithOidcMethod(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "method" in value;

    return isInstance;
}

export function UpdateSettingsFlowWithOidcMethodFromJSON(json: any): UpdateSettingsFlowWithOidcMethod {
    return UpdateSettingsFlowWithOidcMethodFromJSONTyped(json, false);
}

export function UpdateSettingsFlowWithOidcMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSettingsFlowWithOidcMethod {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'flow': !exists(json, 'flow') ? undefined : json['flow'],
        'link': !exists(json, 'link') ? undefined : json['link'],
        'method': json['method'],
        'traits': !exists(json, 'traits') ? undefined : json['traits'],
        'unlink': !exists(json, 'unlink') ? undefined : json['unlink'],
    };
}

export function UpdateSettingsFlowWithOidcMethodToJSON(value?: UpdateSettingsFlowWithOidcMethod | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'flow': value.flow,
        'link': value.link,
        'method': value.method,
        'traits': value.traits,
        'unlink': value.unlink,
    };
}

